### ISSUE TITLE
Css compiler or maybe htm transpiler failed

### ISSUE THREAD

**Issue by DrMabuse23** [electrode-io/generator-electrode#45]
Hi i have something wrong on css: 

with the follwing css:
```css
.home {
  width: 100%;
  height: 100%;
  background-image: url('../assets/img/istock_000012629850xlarge.jpg');
  background-size: cover;
  background-repeat: no-repeat;
}
```
is compiled to 
```css
._2VZCipEERAMHkHlssVRXD4 {
  width: 100%;
  height: 100%;
  background-image: url(http://localhost:2992/js/a676f5cab73be11d829bfe8327d6433f.jpg);
  background-size: cover;
  background-repeat: no-repeat;
}
````

but my `<div className="home"></div>` already `<div class="home" `

I do something wrong ?
